- name: "Deploy Application in Tomcat Servers"
  hosts: tomcat:&phillyapp:&{{ environment | default('dev') }}
  gather_facts: true
  become: true

  roles:
    - role: victorock.linux
      autorun: yes
    - role: victorock.tomcat
      autorun: yes
    - role: victorock.java-webapp
      autorun: yes
