- name: "Deploy Application in JBOSS Servers"
  hosts: phillyapp:&jboss-servers:&{{ environment | default('dev') }}
  gather_facts: true
  become: true

  roles:
    - role: victorock.linux
      autorun: yes
    - role: samdoran.java
    - role: samdoran.repo-epel
    - role: openstack.redhat-subscription
    - role: jboss-jws3

  tasks:

    - name: "Deploy Philly Application from maven"
      maven_artifact:
        group_id:       "com.phillyair"
        artifact_id:    "phillyapp"
        repository_url: "{{ artifactory_server_url }}"
        version:        "{{ app_release }}"
        dest:           "{{ jboss_jws3_home }}/webapps/phillyapp.war"

    - name: "Pause Playbook"
      pause:
        seconds: 10

    - name: "GET webpage content from application"
      uri:
        url: "http://localhost"
        return_content: yes
      register: webpage

    - name: "Assert test the webpage content"
      assert:
        msg: "Webcontent does not contains 'Version: {{ app_release }}'"
        that:
          - "'Version: {{ app_release }}' not in webpage.content"
