- name: "Deploy Application in Tomcat Servers"
  hosts: phillyapp:&tomcat-servers:&{{ environment | default('dev') }}
  gather_facts: true
  become: true

  roles:
    - role: victorock.linux
      autorun: yes
    - role: samdoran.repo-epel
    - role: openstack.redhat-subscription
    - role: victorock.tomcat
    - role: victorock.java-webapp
